In [72]:
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

### keras

In [73]:
model=Sequential()

In [74]:
model.add(Dense(units=1, activation='linear', input_dim=1))

In [75]:
model.summary()

Model: "sequential_6"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_24 (Dense)            (None, 1)                 2         
                                                                 
Total params: 2
Trainable params: 2
Non-trainable params: 0
_________________________________________________________________


In [76]:
model.weights

[<tf.Variable 'dense_24/kernel:0' shape=(1, 1) dtype=float32, numpy=array([[1.5476652]], dtype=float32)>,
 <tf.Variable 'dense_24/bias:0' shape=(1,) dtype=float32, numpy=array([0.], dtype=float32)>]

In [77]:
model.predict([[11],[12],[13]])

array([[17.024317],
       [18.571983],
       [20.119648]], dtype=float32)

### 보스턴 집값 예측

In [78]:
from sklearn import datasets

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\feature_extraction\image.py:167: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype=np.int):


In [81]:
boston=datasets.load_boston()

In [83]:
X_data=boston.data

In [84]:
y_data=boston.target

In [85]:
X_data

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]])

In [86]:
print(X_data.shape, y_data.shape)

(506, 13) (506,)


In [87]:
y_data[:3]

array([24. , 21.6, 34.7])

In [88]:
X_data[0]

array([6.320e-03, 1.800e+01, 2.310e+00, 0.000e+00, 5.380e-01, 6.575e+00,
       6.520e+01, 4.090e+00, 1.000e+00, 2.960e+02, 1.530e+01, 3.969e+02,
       4.980e+00])

In [90]:
boston.keys()

dict_keys(['data', 'target', 'feature_names', 'DESCR', 'filename'])

In [91]:
boston.feature_names

array(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD',
       'TAX', 'PTRATIO', 'B', 'LSTAT'], dtype='<U7')

In [97]:
# 전처리

In [98]:
from sklearn.preprocessing import MinMaxScaler

In [101]:
min_max=MinMaxScaler()
x_data_min_max=min_max.fit_transform(X_data)

In [102]:
x_data_min_max[0]

array([0.        , 0.18      , 0.06781525, 0.        , 0.31481481,
       0.57750527, 0.64160659, 0.26920314, 0.        , 0.20801527,
       0.28723404, 1.        , 0.08967991])

In [93]:
# 딥러닝 모델 만들어서

In [103]:
model2=Sequential()

In [104]:
model2.add(Dense(units=128, activation='relu', input_dim=13))
model2.add(Dense(units=64, activation='relu'))
model2.add(Dense(units=1, activation='linear'))

In [105]:
# 위에서 쌓은 모델로 설정

In [106]:
model2.compile(optimizer='adam', loss='mse', metrics=['mae'])

In [107]:
model2.summary()

Model: "sequential_7"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_25 (Dense)            (None, 128)               1792      
                                                                 
 dense_26 (Dense)            (None, 64)                8256      
                                                                 
 dense_27 (Dense)            (None, 1)                 65        
                                                                 
Total params: 10,113
Trainable params: 10,113
Non-trainable params: 0
_________________________________________________________________


In [94]:
# 공부시키고

In [116]:
model2.fit(x_data_min_max[:400], y_data[:400], epochs=3, batch_size=50, verbose=2)
# epochs -> 3번 순환
# batch_sieze -> 가중치를 데이터 50개마다 다시 계산

Epoch 1/3
8/8 - 0s - loss: 57.5440 - mae: 5.4932 - 7ms/epoch - 873us/step
Epoch 2/3
8/8 - 0s - loss: 55.3124 - mae: 5.3703 - 9ms/epoch - 1ms/step
Epoch 3/3
8/8 - 0s - loss: 53.4355 - mae: 5.2601 - 7ms/epoch - 873us/step


In [95]:
# 정확도 계산

In [117]:
model2.evaluate(x_data_min_max[400:], y_data[400:])

4/4 [==============================] - 0s 2ms/step - loss: 25.0226 - mae: 3.9656


[25.022605895996094, 3.965575933456421]

In [96]:
# 예측