In [2]:
import warnings
warnings.filterwarnings('ignore')
from sklearn.preprocessing import StandardScaler #표준화(평균을 기준)
from sklearn.preprocessing import MinMaxScaler   #정규화(정해진 규칙 기준, min-max)
from sklearn.datasets import load_iris

import time
from IPython.display import Image
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier

from sklearn.model_selection import cross_val_score
# cross_val_score: 다양한 샘플링을 해서 여러번 테스트 --> 평균치를 구해본다.!
from sklearn.metrics import *

from sklearn.model_selection import GridSearchCV

from sklearn.preprocessing import LabelEncoder
from matplotlib import rc, font_manager
import matplotlib.font_manager as fm

# 디렉토리 및 파일 이름에 맞추어 변경
font_location = 'C:/Windows/Fonts/malgun.ttf'

font_name = fm.FontProperties(fname=font_location).get_name()
rc('font', family=font_name)

In [3]:
# data12 - 기계마모
# data14 - 앙상블voting, 서울시구별영역나누기
# 위 코드들 이용하여 머신러닝 모델 만들기

In [4]:
df=pd.read_csv('국내여행_병합.csv')

In [6]:
df

Unnamed: 0  year  target_area1  target_area2  target_area3  \
0              0  2018         99999             0             0   
1              1  2018         32390             0             0   
2              2  2018         31370             0             0   
3              3  2018         31370             0             0   
4              4  2018         99999             0             0   
...          ...   ...           ...           ...           ...   
5152        5152  2020         39020             0             0   
5153        5153  2020         39010             0             0   
5154        5154  2020         21070             0             0   
5155        5155  2020         39010             0             0   
5156        5156  2020         39010         39010             0   

      target_area4  target_area5  target_area6  target_area7  target_area8  \
0                0             0             0             0             0   
1                0             0             0             0             0   
2                0             0             0             0             0   
3                0             0             0             0             0   
4                0             0             0             0             0   
...            ...           ...           ...           ...           ...   
5152             0             0             0             0             0   
5153             0             0             0             0             0   
5154             0             0             0             0             0   
5155             0             0             0             0             0   
5156             0             0             0             0             0   

      ...  transportation1  transportation2  transportation3  reason1  \
0     ...                1                0                0       14   
1     ...                1                0                0        1   
2     ...                6                0                0        4   
3     ...                2                0                0        1   
4     ...                1                0                0       13   
...   ...              ...              ...              ...      ...   
5152  ...                6                0                0        1   
5153  ...                1                0                0       14   
5154  ...                3                6                0       15   
5155  ...                1                0                0       15   
5156  ...                1                2                0        1   

      reason2  reason3  relationship1  relationship2  relationship3  target  
0           1       11              1              0              0  힐링,호캉스  
1          11        9              1              0              0  힐링,호캉스  
2          14        5              3              0              0    엑티비티  
3           5        8              3              0              0  힐링,호캉스  
4          14        3              1              0              0  힐링,호캉스  
...       ...      ...            ...            ...            ...     ...  
5152       14        0              3              0              0    엑티비티  
5153        0        0              3              0              0    엑티비티  
5154        0        0              0              0              0    엑티비티  
5155        0        0              0              0              0  힐링,호캉스  
5156        0        0              3              0              0  힐링,호캉스  

[5157 rows x 43 columns]

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5157 entries, 0 to 5156
Data columns (total 43 columns):
 #   Column              Non-Null Count  Dtype 
---  ------              --------------  ----- 
 0   Unnamed: 0          5157 non-null   int64 
 1   year                5157 non-null   int64 
 2   target_area1        5157 non-null   int64 
 3   target_area2        5157 non-null   int64 
 4   target_area3        5157 non-null   int64 
 5   target_area4        5157 non-null   int64 
 6   target_area5        5157 non-null   int64 
 7   target_area6        5157 non-null   int64 
 8   target_area7        5157 non-null   int64 
 9   target_area8        5157 non-null   int64 
 10  target_area9        5157 non-null   int64 
 11  target_area10       5157 non-null   int64 
 12  target_area11       5157 non-null   int64 
 13  no_of_place         5157 non-null   int64 
 14  sleepnights_1       5157 non-null   int64 
 15  sleepnights_2       5157 non-null   int64 
 16  sleepnights_3       5157

In [8]:
del df['Unnamed: 0']

In [16]:
df.iloc[:,:-1].head()

year  target_area1  target_area2  target_area3  target_area4  target_area5  \
0  2018         99999             0             0             0             0   
1  2018         32390             0             0             0             0   
2  2018         31370             0             0             0             0   
3  2018         31370             0             0             0             0   
4  2018         99999             0             0             0             0   

   target_area6  target_area7  target_area8  target_area9  ...  living_area  \
0             0             0             0             0  ...           11   
1             0             0             0             0  ...           11   
2             0             0             0             0  ...           11   
3             0             0             0             0  ...           11   
4             0             0             0             0  ...           11   

   transportation1  transportation2  transportation3  reason1  reason2  \
0                1                0                0       14        1   
1                1                0                0        1       11   
2                6                0                0        4       14   
3                2                0                0        1        5   
4                1                0                0       13       14   

   reason3  relationship1  relationship2  relationship3  
0       11              1              0              0  
1        9              1              0              0  
2        5              3              0              0  
3        8              3              0              0  
4        3              1              0              0  

[5 rows x 41 columns]

In [17]:
df.columns

Index(['year', 'target_area1', 'target_area2', 'target_area3', 'target_area4',
       'target_area5', 'target_area6', 'target_area7', 'target_area8',
       'target_area9', 'target_area10', 'target_area11', 'no_of_place',
       'sleepnights_1', 'sleepnights_2', 'sleepnights_3', 'sleepnights_4',
       'sleepnights_5', 'sleepnights_6', 'sleepnights_7', 'sleepnights_8',
       'accommodation_1', 'accommodation_2', 'accommodation_3',
       'number_of_ppl', 'number_of_children', 'cost_total_trip', 'satisfied',
       'sex', 'age', 'month', 'living_area', 'transportation1',
       'transportation2', 'transportation3', 'reason1', 'reason2', 'reason3',
       'relationship1', 'relationship2', 'relationship3', 'target'],
      dtype='object')

In [18]:
data=df[['year', 'target_area1', 'target_area2', 'target_area3', 'target_area4',
       'target_area5', 'target_area6', 'target_area7', 'target_area8',
       'target_area9', 'target_area10', 'target_area11', 'no_of_place',
       'sleepnights_1', 'sleepnights_2', 'sleepnights_3', 'sleepnights_4',
       'sleepnights_5', 'sleepnights_6', 'sleepnights_7', 'sleepnights_8',
       'accommodation_1', 'accommodation_2', 'accommodation_3',
       'number_of_ppl', 'number_of_children', 'cost_total_trip', 'satisfied',
       'sex', 'age', 'month', 'living_area', 'transportation1',
       'transportation2', 'transportation3', 'reason1', 'reason2', 'reason3',
       'relationship1', 'relationship2', 'relationship3']]
target=df['target']

In [19]:
X_train, X_test, y_train, y_test=train_test_split(
    data,
    target,
    test_size=0.2,
    random_state=50
)

In [20]:
X_train.shape, y_train.shape, X_test.shape, y_test.shape

((4125, 41), (4125,), (1032, 41), (1032,))

In [21]:
knn=KNeighborsClassifier()
svm=SVC()
dt=DecisionTreeClassifier()
model_list=[knn, svm, dt]

In [22]:
def print_cv(model, train, target, k):
    scores=cross_val_score(model, train, target, cv=k)
    print('----교차검증(cv)결과 리스트----\n',scores)
    mean_scores=np.mean(scores)
    print('----교차검증(cv)결과 평균----\n',mean_scores)
    return scores, mean_scores 
    
    ## 함수의 결과로 여러개의 데이터를 return할 수 있다.
    ## 튜플로 묶어서 반환하게 된다.(scores, mean_scores)

In [23]:
model_names=['KNeighborsClassifier','SVC','DecisionTreeClassifier']
sc_list=[]
mean_sc_list=[]
for model in model_list:
    sc, mean_sc=print_cv(model, X_train, y_train, 5)
    sc_list.append(sc)
    mean_sc_list.append(mean_sc)
print('***************************************')
print('----전체 모델 리스트----')
print(model_names)
print('----전체 모델의 교차검증 결과 리스트----')
print(sc_list)
print('----전체 모델의 교차검증 결과 평균----')
print(mean_sc_list)

----교차검증(cv)결과 리스트----
 [0.59613059 0.59129383 0.58545455 0.59295261 0.62332928]
----교차검증(cv)결과 평균----
 0.5978321733187246
----교차검증(cv)결과 리스트----
 [0.65296252 0.6541717  0.6569697  0.65735115 0.65735115]
----교차검증(cv)결과 평균----
 0.6557612451338446
----교차검증(cv)결과 리스트----
 [0.5719468  0.59250302 0.59272727 0.56865128 0.60631835]
----교차검증(cv)결과 평균----
 0.5864293429356159
***************************************
----전체 모델 리스트----
['KNeighborsClassifier', 'SVC', 'DecisionTreeClassifier']
----전체 모델의 교차검증 결과 리스트----
[array([0.59613059, 0.59129383, 0.58545455, 0.59295261, 0.62332928]), array([0.65296252, 0.6541717 , 0.6569697 , 0.65735115, 0.65735115]), array([0.5719468 , 0.59250302, 0.59272727, 0.56865128, 0.60631835])]
----전체 모델의 교차검증 결과 평균----
[0.5978321733187246, 0.6557612451338446, 0.5864293429356159]


## svc

In [24]:
def grid_search(model, params, k):
    gs_model=GridSearchCV(model, params, cv=k)
    ## gs_model은 최적의 파라미터가 적용된 모델의 객체!
    gs_model.fit(X_train, y_train)
    print(gs_model.best_estimator_) ## 최적의 파라미터가 적용된 모델 객체
    print(gs_model.best_score_) ## 최적의 파라미터가 적용된 모델로 학습한 정확도 결과(acc)
    print(gs_model.best_params_) ## 그리드 서치를 통해 찾은 최적의 파라미터
    print(gs_model) ## grid_search 객체

In [25]:
params={ 
    'C': [0.001, 0.01, 0.1, 1, 10, 25],
    'random_state':[5, 50, 99]
}

In [26]:
grid_search(svm, params, 5)

SVC(C=10, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='rbf', max_iter=-1, probability=False, random_state=5,
    shrinking=True, tol=0.001, verbose=False)
0.6564848484848484
{'C': 10, 'random_state': 5}
GridSearchCV(cv=5, error_score='raise-deprecating',
             estimator=SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='auto_deprecated', kernel='rbf', max_iter=-1,
                           probability=False, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='warn', n_jobs=None,
             param_grid={'C': [0.001, 0.01, 0.1, 1, 10, 25],
                         'random_state': [5, 50, 99]},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)


In [27]:
gs_svm=SVC(C=10, random_state=5)
gs_svm.fit(X_train, y_train)

SVC(C=10, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='rbf', max_iter=-1, probability=False, random_state=5,
    shrinking=True, tol=0.001, verbose=False)

In [28]:
def test_validation(model, X_test, y_test):
    predict_result=model.predict(X_test)
    acc=accuracy_score(y_test, predict_result)
    print('accuracy >>', acc)
    cf=confusion_matrix(y_test, predict_result)
    print('confusion matrix >>\n', cf)
    ## confusion matrix는 binary classfication인 경우에는 보기가 괜찮으나,
    ## multi class classification인 경우에는 보기가 힘들다.
    ## confusion matrix를 가독성 좋에 볼 수 있는 것이 classification_report
    c_report=classification_report(y_test, predict_result)
    print('classification_report >>\n', c_report)

In [29]:
test_validation(gs_svm, X_test, y_test)

accuracy >> 0.6802325581395349
confusion matrix >>
 [[  1   1   0 115]
 [  1   2   0 154]
 [  0   0   0  58]
 [  0   0   1 699]]
classification_report >>
               precision    recall  f1-score   support

    식도락,맛집투어       0.50      0.01      0.02       117
        엑티비티       0.67      0.01      0.03       157
       축제,관광       0.00      0.00      0.00        58
      힐링,호캉스       0.68      1.00      0.81       700

    accuracy                           0.68      1032
   macro avg       0.46      0.25      0.21      1032
weighted avg       0.62      0.68      0.56      1032

